import type { Metadata } from "next";
import "./globals.css";
import AuthSession from "@/app/_component/AuthSession";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = {
    children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
    return (
        <html>
            <body className="layout-default">
                <header className="header">I am 넥스트에요</header>
                <AuthSession>{children}</AuthSession>
            </body>
        </html>
    );
}
